#!/bin/bash

echo Deleting cpp and pyd files in Cielab directory prior installation
cd Cielab
rm *.cpp
rm *.pyd
rm *.so
cd ..

python3.6 setup.py build_ext --inplace && python3.6 setup.py bdist_wheel

cd Cielab
rm *.cpp
rm *.so
cd ..

python3.7 setup.py build_ext --inplace && python3.7 setup.py bdist_wheel


cd Cielab
rm *.cpp
rm *.so
cd ..

python3.8 setup.py build_ext --inplace && python3.8 setup.py bdist_wheel


cd Cielab
rm *.cpp
rm *.so
cd ..

python3.9 setup.py build_ext --inplace && python3.9 setup.py bdist_wheel


cd Cielab
rm *.cpp
rm *.so
cd ..

python3.10 setup.py build_ext --inplace && python3.10 setup.py bdist_wheel


cd Cielab
rm *.cpp
rm *.so
cd ..

python3.11 setup.py build_ext --inplace && python3.11 setup.py sdist bdist_wheel

cd Cielab
rm *.cpp
rm *.so
cd ..


